on: 
  Workflow_dispatch
    inputs:
      environments:
        -name: dev
         type: boolean
         default: true
         
        -name: val
         type: boolean
         default: true
         
          -name: prod
         type: boolean
         default: true
      
jobs: 

  build:
  runs-on: ubuntu-latest
  
  steps:
  - uses: actions/checkout@V2
  
  - run: |
      run: mvn -B package --file jenkins/pom.xml
  
